---
- name: Restart tower if drop rate too high
  hosts: localhost

  sources:
    - name: Listen for dropped call events
      ansible.eda.kafka:
        topic: "{{ kafka_topic | default('dropped-alerts') }}"
        host: "{{ kafka_url | default('my-cluster-kafka-bootstrap.openshift-operators.svc') }}" 
        group_id: eda-listener
        port: 9092
        deserialize: json

  rules:
    - name: Detect down cell tower
      condition: event.body.dropRate > 0.1
      action:
        debug:
          msg: "Tower {{ event.body.cell_id }} is down. Remediating.."

    - name: Print event
      condition: event.body is defined
      action:
        debug:
          msg: "Received tower drop event: {{ event.body }} "
