---
- name: Restart tower if drop rate too high
  hosts: localhost

  sources:
    - name: Listen for dropped call events
      ansible.eda.kafka:
        topic: "{{ kafka_topic | default('dropped_alerts') }}"
        host: "{{ kafka_url | default('my-cluster-kafka-bootstrap.openshift-operators.svc') }}" 
        group_id: eda-listener
        port: 9092
        deserialize: json

  rules:
    - name: Print Hello on Any Event
      condition: event.body.dropRate > .1
      action:
        debug:
          msg: "Tower {{ event.body.cell_id }} is down. Remediating.."
