---
- name: Restart tower simulator pod
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Delete the pod (so OpenShift restarts it)
      kubernetes.core.k8s:
        state: absent
        kind: Pod
        namespace: telco-demo
        name: tower-tx-01
