---
- name: Restart tower simulator pod
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Delete the pod (so OpenShift restarts it)
      kubernetes.core.k8s:
        state: absent
        kind: Pod
        namespace: openshift-operators
        name: call-record-generator-amd64
